### ISSUE TITLE
Update setup document link to new location

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats-Setup#1]
We're still pointing the setup document link to GDrive.
Can you update it to an appropriate new location? (SS_TeamSpace is probably right, right?)

**Comment by kjacobsen16** [comment]
The current document is in the WIM sharepoint [here](https://doimspp.sharepoint.com/sites/GS-UMidWIM/Shared%20Documents/Forms/AllItems.aspx?viewid=144f35a1%2D90d4%2D4ed2%2D9f31%2D521ec6887304&id=%2Fsites%2FGS%2DUMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FSS%20Cloud%20Infrastructure). Is looks like there are a few things that should be moved over to the SS_Teamsace instead, like the GIS team credentials and arctoolbox folder.
