### ISSUE TITLE
Document/Clean Up Process for updating map services

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-Setup#2]
The process for updating the state service is documented at `D:/mapservices/steps to update stateServices.txt`, this process should be cleaned up and moved to a repo

**Comment by harper-wavra** [comment]
This is documented here: https://doimspp.sharepoint.com/sites/GS-UMidWIM/_layouts/OneNote.aspx?id=%2Fsites%2FGS-UMidWIM%2FShared%20Documents%2FProjects%2FStreamstats%20Ecosystem%2FKJ%27s%20Guide%20to%20StreamStats%201&wd=target%28FAQs.one%7CD8FCAEF7-3539-4FED-A0C2-5BCBE0E4F155%2FHow%20do%20I%20update%20a%20map%20service%3F%7C69031375-0326-40AE-A521-3C22583A8A27%2F%29
