### ISSUE TITLE
Update testsites.geojson

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-Setup#3]
https://github.com/USGS-WiM/StreamStats-Setup/blob/master/batchTester/testSites.geojson

the list is missing MO (I used MO,-92.77203,39.41615,06906470 for integration testing) , and there are a lot of basin characteristics that are either not in here or likely have outdated values.

Pete also wants to add some globals to test

Also need a site for PR (I used PR,-66.45962,18.32206,50035000 for the integration testing

**Comment by kjacobsen16** [comment]
MO and PR added, and basin characteristics updated.

No globals have been added yet - we might be able to pull these out of the spreadsheet [here](https://doimspp.sharepoint.com/:x:/r/sites/StreamStatsTeam/_layouts/15/Doc.aspx?sourcedoc=%7BC4771B38-148D-4B20-98EC-0DB78C41E0C7%7D&file=GlobalTestv52.xlsx&action=default&mobileredirect=true&cid=07a03019-3489-4c2b-a313-996eded8032d)

**Comment by amedenblik** [comment]
Closing in favor of #29
