### ISSUE TITLE
Statistic Label updates

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/StreamStats-Setup#33]
https://test.streamstats.usgs.gov/statistic-labels/statistic-types

- [ ] Rename page
- [ ] Add distinct URLs for each tab (either unique pages or via URL parameters)
- [ ] Auto-fill URL parameter `?region=AZ' etc for regions
- [ ] Add citations

**Comment by harper-wavra** [comment]
Moved to https://code.usgs.gov/StreamStats/clients/information-portal/-/issues/
